import json
import logging
import os
from typing import AsyncIterator

import gradio as gr
import httpx

logger = logging.getLogger(__name__)

API_BASE_URL = os.getenv("RAG_API_BASE_URL", "http://localhost:8000/api/v1")
DEFAULT_MODEL = "llama3.2"
REQUEST_TIMEOUT = httpx.Timeout(connect=10.0, read=300.0, write=10.0, pool=10.0)


async def stream_response(
    query: str,
    top_k: int = 3,
    use_hybrid: bool = True,
    model: str = DEFAULT_MODEL,
    categories: str = "",
) -> AsyncIterator[str]:
    """Stream response from the RAG API."""
    if not query.strip():
        yield "Please enter a question."
        return

    category_list = [cat.strip() for cat in categories.split(",") if cat.strip()] if categories else None
    payload = {
        "question": query,
        "top_k": top_k,
        "use_hybrid": use_hybrid,
        "model": model,
        "categories": category_list,
    }

    yield "_Searching papers and generating answer... This may take 1-2 minutes on local Ollama._"

    try:
        url = f"{API_BASE_URL}/stream"
        async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
            async with client.stream("POST", url, json=payload) as response:
                if response.status_code != 200:
                    body = await response.aread()
                    yield f"**Error:** API returned status {response.status_code}: {body.decode()}"
                    return

                current_answer = ""
                sources: list[str] = []
                chunks_used = 0
                search_mode = ""

                async for line in response.aiter_lines():
                    if not line.startswith("data: "):
                        continue

                    try:
                        data = json.loads(line[6:])
                    except json.JSONDecodeError:
                        continue

                    if "error" in data:
                        yield f"**Error:** {data['error']}"
                        return

                    if "sources" in data:
                        sources = data["sources"]
                        chunks_used = data.get("chunks_used", 0)
                        search_mode = data.get("search_mode", "unknown")
                        yield (
                            f"_Retrieved {chunks_used} chunks via {search_mode} search. "
                            f"Generating answer with Ollama..._"
                        )
                        continue

                    if "chunk" in data:
                        current_answer += data["chunk"]
                        yield _format_response(current_answer, sources, chunks_used, search_mode)

                    if data.get("done", False):
                        final_answer = data.get("answer", current_answer)
                        yield _format_response(final_answer, sources, chunks_used, search_mode)
                        return

                if not current_answer:
                    yield "**Error:** Stream ended without a response. Ollama may still be loading the model."

    except httpx.ReadTimeout:
        yield (
            "**Error:** Request timed out waiting for Ollama. "
            "Try fewer chunks (top_k=2) or a smaller model like `llama3.2:1b`."
        )
    except httpx.ConnectError:
        yield (
            f"**Connection error:** Cannot reach the API at `{API_BASE_URL}`.\n\n"
            "Make sure the API is running:\n"
            "```bash\ndocker compose up -d api\n```"
        )
    except httpx.RequestError as e:
        yield f"**Connection error:** {e}\n\nAPI URL: `{API_BASE_URL}`"
    except Exception as e:
        logger.exception("Gradio stream error")
        yield f"**Unexpected error:** {e}"


def _format_response(answer: str, sources: list[str], chunks_used: int, search_mode: str) -> str:
    formatted = answer
    if sources or chunks_used:
        formatted += "\n\n**Search Info:**\n"
        formatted += f"- Mode: {search_mode}\n"
        formatted += f"- Chunks used: {chunks_used}\n"
        if sources:
            formatted += f"- Sources: {len(sources)} papers\n"
            for i, source in enumerate(sources[:3], 1):
                formatted += f"  {i}. [{source.split('/')[-1]}]({source})\n"
            if len(sources) > 3:
                formatted += f"  ... and {len(sources) - 3} more\n"
    return formatted


def create_gradio_interface():
    with gr.Blocks(title="arXiv Paper Curator - RAG Chat") as interface:
        gr.Markdown(
            """
            # arXiv Paper Curator - RAG Chat

            Ask questions about CS.AI papers indexed from arXiv.
            Answers are generated by Ollama using retrieved paper chunks.

            **Note:** Local Ollama can take 1-2 minutes per answer. Use `http://localhost:7861` (not the share link).
            """
        )

        with gr.Row():
            with gr.Column(scale=3):
                query_input = gr.Textbox(
                    label="Your Question",
                    placeholder="What is transformer attention?",
                    lines=2,
                )
            with gr.Column(scale=1):
                submit_btn = gr.Button("Ask Question", variant="primary")

        with gr.Accordion("Advanced Options", open=False):
            top_k = gr.Slider(1, 10, value=3, step=1, label="Chunks to retrieve")
            use_hybrid = gr.Checkbox(value=True, label="Use hybrid search (BM25 + vectors)")
            model_choice = gr.Dropdown(
                choices=["llama3.2", "llama3.2:1b", "llama3.2:3b", "mistral"],
                value=DEFAULT_MODEL,
                label="Ollama model",
            )
            categories = gr.Textbox(
                label="arXiv categories (optional)",
                placeholder="cs.AI, cs.LG",
            )

        response_output = gr.Markdown(label="Answer", value="Ask a question to get started!")

        gr.Examples(
            examples=[
                ["What is transformer attention?", 3, True, "llama3.2", "cs.AI"],
                ["How does reinforcement learning work?", 3, True, "llama3.2", "cs.AI, cs.LG"],
                ["What are diffusion models?", 3, False, "llama3.2", "cs.AI"],
            ],
            inputs=[query_input, top_k, use_hybrid, model_choice, categories],
        )

        submit_btn.click(
            fn=stream_response,
            inputs=[query_input, top_k, use_hybrid, model_choice, categories],
            outputs=[response_output],
        )
        query_input.submit(
            fn=stream_response,
            inputs=[query_input, top_k, use_hybrid, model_choice, categories],
            outputs=[response_output],
        )

    return interface


def main():
    server_name = os.getenv("GRADIO_SERVER_NAME", "0.0.0.0")
    server_port = int(os.getenv("GRADIO_SERVER_PORT", "7861"))

    print("Starting arXiv Paper Curator Gradio Interface...")
    print(f"API Base URL: {API_BASE_URL}")
    print(f"Open http://localhost:{server_port} in your browser")
    interface = create_gradio_interface()
    interface.launch(
        server_name=server_name,
        server_port=server_port,
        share=False,
        theme=gr.themes.Soft(),
    )


if __name__ == "__main__":
    main()
